const FoodData = [
    {
        id : 1,
        image : "images/maggi.jpg",
        name : 'Maggi',
        category : "breakfast",
        price : "₹ 20",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },
    {
        id : 2,
        image : "images/pizza.jpg",
        name : 'Pizza',
        category : "dinner",
        price : "₹ 170" ,
        description : "Jalfrezi is an Indian technique for preparing a type of curry made by frying",
    },
    {
        id : 3,
        image : "images/corn.jpg",
        name : 'Corn',
        category : "breakfast",
        price : "₹ 30 ",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.",
    },
    {
        id : 4,
        image : "images/panner.jpg",
        name : 'Panner',
        category : "dinner",
        price : "₹ 180" ,
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },
    {
        id : 5,
        image : "images/jalfarzi.jpg",
        name : 'Jalfarzi',
        category : "evening",
        price : "₹ 250",
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },
    {
        id : 6,
        image : "images/non-veg.jpg",
        name : 'Non-veg Thali',
        category : "dinner",
        price : "₹ 499",
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },
    {
        id : 7,
        image : "images/rajma.jpg",
        name : 'Rajma Chawal',
        category : "lunch",
        price : "₹ 99",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.",
    },
    {
        id : 8,
        image : "images/samosha.jpg",
        name : 'Samosha',
        category : "evening",
        price : "₹ 29",
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },
    {
        id : 9,
        image : "images/vegthali.jpg",
        name : 'Veg Thali',
        category : "lunch",
        price : "₹ 149" ,
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.",
    },
    {
        id : 10,
        image : "images/chai.jpg",
        name : 'Chai',
        category : "breakfast",
        price : "₹15",
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.",
    },
    {
        id : 11,
        image : "images/bhature.jpg",
        name : 'Bhature',
        category : "breakfast",
        price : "₹69",
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },
    {
        id : 12,
        image : "images/burger.jpg",
        name : 'Burger',
        category : "evening",
        price : "₹ 79",
        description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod." ,
    },

]


export default FoodData